#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Class-Tiny
Version  : 1.008
Release  : 38
URL      : https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.008.tar.gz
Summary  : 'Minimalist class construction'
Group    : Development/Tools
License  : Apache-2.0
Requires: perl-Class-Tiny-license = %{version}-%{release}
Requires: perl-Class-Tiny-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Class::Tiny - Minimalist class construction
VERSION
version 1.008
SYNOPSIS
In Person.pm:

%package dev
Summary: dev components for the perl-Class-Tiny package.
Group: Development
Provides: perl-Class-Tiny-devel = %{version}-%{release}
Requires: perl-Class-Tiny = %{version}-%{release}

%description dev
dev components for the perl-Class-Tiny package.


%package license
Summary: license components for the perl-Class-Tiny package.
Group: Default

%description license
license components for the perl-Class-Tiny package.


%package perl
Summary: perl components for the perl-Class-Tiny package.
Group: Default
Requires: perl-Class-Tiny = %{version}-%{release}

%description perl
perl components for the perl-Class-Tiny package.


%prep
%setup -q -n Class-Tiny-1.008
cd %{_builddir}/Class-Tiny-1.008

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-Tiny
cp %{_builddir}/Class-Tiny-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Class-Tiny/e188c4892bc1fbfced62c2299a2a24fd21098d81 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::Tiny.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-Tiny/e188c4892bc1fbfced62c2299a2a24fd21098d81

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
