#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Class-Tiny
Version  : 1.006
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.006.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.006.tar.gz
Summary  : 'Minimalist class construction'
Group    : Development/Tools
License  : Apache-2.0
Requires: perl-Class-Tiny-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
Class::Tiny - Minimalist class construction
VERSION
version 1.006
SYNOPSIS
In Person.pm:

%package dev
Summary: dev components for the perl-Class-Tiny package.
Group: Development
Provides: perl-Class-Tiny-devel = %{version}-%{release}

%description dev
dev components for the perl-Class-Tiny package.


%package license
Summary: license components for the perl-Class-Tiny package.
Group: Default

%description license
license components for the perl-Class-Tiny package.


%prep
%setup -q -n Class-Tiny-1.006

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-Tiny
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Class-Tiny/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Class/Tiny.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::Tiny.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-Tiny/LICENSE
